# Generated by Django 4.2.7 on 2025-09-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên widget')),
                ('widget_type', models.CharField(choices=[('chart', 'Biểu đồ'), ('table', 'Bảng'), ('metric', 'Số liệu'), ('list', 'Danh sách')], max_length=20, verbose_name='Loại widget')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('config', models.JSONField(default=dict, verbose_name='Cấu hình')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Vị trí')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Widget Dashboard',
                'verbose_name_plural': 'Widget Dashboard',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('start_date', models.DateField(verbose_name='Từ ngày')),
                ('end_date', models.DateField(verbose_name='Đến ngày')),
                ('data', models.JSONField(default=dict, verbose_name='Dữ liệu báo cáo')),
                ('summary', models.JSONField(default=dict, verbose_name='Tóm tắt')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Báo cáo đã tạo',
                'verbose_name_plural': 'Báo cáo đã tạo',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên mẫu báo cáo')),
                ('report_type', models.CharField(choices=[('revenue', 'Báo cáo doanh thu'), ('expense', 'Báo cáo chi phí'), ('appointment', 'Báo cáo lịch hẹn'), ('customer', 'Báo cáo khách hàng'), ('service', 'Báo cáo dịch vụ'), ('doctor', 'Báo cáo bác sĩ'), ('branch', 'Báo cáo chi nhánh')], max_length=20, verbose_name='Loại báo cáo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('filters', models.JSONField(default=dict, verbose_name='Bộ lọc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mẫu báo cáo',
                'verbose_name_plural': 'Mẫu báo cáo',
                'ordering': ['name'],
            },
        ),
    ]
