# Generated by Django 4.2.7 on 2025-09-10 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Ngày hẹn')),
                ('appointment_time', models.TimeField(verbose_name='Giờ hẹn')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Thời gian (phút)')),
                ('status', models.CharField(choices=[('scheduled', 'Đã đặt lịch'), ('confirmed', 'Đã xác nhận'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('no_show', 'Không đến')], default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=50, verbose_name='Loại thay đổi')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Giá trị cũ')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Giá trị mới')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='appointments.appointment', verbose_name='Lịch hẹn')),
            ],
            options={
                'verbose_name': 'Lịch sử lịch hẹn',
                'verbose_name_plural': 'Lịch sử lịch hẹn',
                'ordering': ['-created_at'],
            },
        ),
    ]
