# Generated by Django 4.2.7 on 2025-09-19 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('appointments', '0001_initial'), ('appointments', '0002_initial'), ('appointments', '0003_alter_appointment_unique_together'), ('appointments', '0004_alter_appointment_unique_together_and_more'), ('appointments', '0005_alter_appointment_services'), ('appointments', '0006_alter_appointment_status'), ('appointments', '0007_appointment_appointment_type_and_more'), ('appointments', '0008_appointment_services_with_quantity'), ('appointments', '0009_appointment_end_time_and_more'), ('appointments', '0010_appointment_is_waitlist'), ('appointments', '0011_appointment_waitlist_position'), ('appointments', '0012_add_temp_customer_fields_only'), ('appointments', '0013_remove_customer_field')]

    dependencies = [
        ('customers', '0019_customer_status'),
        ('customers', '0001_initial'),
        ('customers', '0008_remove_customer_address_customer_address_old_and_more'),
        ('customers', '0007_remove_customer_preferred_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Ngày hẹn')),
                ('appointment_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Thời gian (phút)')),
                ('status', models.CharField(choices=[('scheduled', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('arrived', 'Khách đã đến'), ('in_progress', 'Đang điều trị'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã huỷ'), ('no_show', 'Khách không đến')], default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.branch', verbose_name='Chi nhánh')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Tạo bởi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Khách hàng')),
                ('doctor', models.ForeignKey(limit_choices_to={'groups__name': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bác sĩ')),
                ('services', models.ManyToManyField(related_name='appointments', to='customers.service')),
                ('appointment_type', models.CharField(choices=[('consultation', 'Tham khảo dịch vụ'), ('treatment', 'Điều trị'), ('follow_up', 'Tái khám'), ('emergency', 'Cấp cứu')], default='consultation', max_length=20, verbose_name='Loại lịch hẹn')),
                ('services_with_quantity', models.JSONField(blank=True, default=list, verbose_name='Dịch vụ với số lượng')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc')),
                ('is_waitlist', models.BooleanField(default=False, verbose_name='Danh sách chờ')),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'ordering': ['-appointment_date', '-appointment_time'],
                'unique_together': {('doctor', 'appointment_date', 'appointment_time')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=50, verbose_name='Loại thay đổi')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Giá trị cũ')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Giá trị mới')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='appointments.appointment', verbose_name='Lịch hẹn')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Thay đổi bởi')),
            ],
            options={
                'verbose_name': 'Lịch sử lịch hẹn',
                'verbose_name_plural': 'Lịch sử lịch hẹn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunSQL(
            sql='ALTER TABLE appointments_appointment ALTER COLUMN waitlist_position DROP NOT NULL;',
            reverse_sql='ALTER TABLE appointments_appointment ALTER COLUMN waitlist_position SET NOT NULL;',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(default='Khách hàng chưa xác định', max_length=200, verbose_name='Tên khách hàng'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Số điện thoại khách hàng'),
        ),
    ]
