# Generated by Django 4.2.7 on 2025-09-11 01:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0007_remove_customer_preferred_service_and_more'),
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_date', 'appointment_time', 'service')},
        ),
    ]
