# Generated by Django 4.2.7 on 2025-09-11 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0007_remove_customer_preferred_service_and_more'),
        ('appointments', '0003_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_date', 'appointment_time')},
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='customers.service', verbose_name='Dịch vụ'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
    ]
