# Generated by Django 4.2.7 on 2025-09-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_customer_address_customer_address_old_and_more'),
        ('appointments', '0004_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='customers.service'),
        ),
    ]
