# Generated by Django 4.2.7 on 2025-09-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('arrived', 'Khách đã đến'), ('in_progress', 'Đang điều trị'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('no_show', 'Không đến')], default='scheduled', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
