# Generated by Django 4.2.7 on 2025-09-12 16:07

from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_status'),
        ('customers', '0008_remove_customer_address_customer_address_old_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=models.deletion.CASCADE, to='appointments.appointment')),
                ('service', models.ForeignKey(on_delete=models.deletion.CASCADE, to='customers.service')),
            ],
            options={
                'db_table': 'appointments_appointment_services',
            },
        ),
    ]
