# Generated by Django 4.2.7 on 2025-09-16 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'Tham khảo dịch vụ'), ('treatment', 'Điều trị'), ('follow_up', 'Tái khám'), ('emergency', 'Cấp cứu')], default='consultation', max_length=20, verbose_name='Loại lịch hẹn'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bác sĩ'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('arrived', 'Khách đã đến'), ('in_progress', 'Đang điều trị'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã huỷ'), ('no_show', 'Khách không đến')], default='scheduled', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
