# Generated by Django 4.2.7 on 2025-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services_with_quantity',
            field=models.JSONField(blank=True, default=list, verbose_name='Dịch vụ với số lượng'),
        ),
    ]
