# Generated by Django 4.2.7 on 2025-09-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20250912_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentServices',
        ),
    ]
