# Generated by Django 4.2.7 on 2025-09-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_delete_appointmentservices'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS appointments_appointment_services (
                id SERIAL PRIMARY KEY,
                appointment_id INTEGER NOT NULL REFERENCES appointments_appointment(id) ON DELETE CASCADE,
                service_id INTEGER NOT NULL REFERENCES customers_service(id) ON DELETE CASCADE,
                UNIQUE(appointment_id, service_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS appointments_appointment_services;"
        ),
    ]
