# Generated by Django 4.2.7 on 2025-09-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_delete_appointmentservices'),
    ]

    operations = [
    ]
