# Generated by Django 4.2.7 on 2025-09-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20250915_1511'),
        ('appointments', '0009_fix_appointment_services'),
    ]

    operations = [
    ]
