# Generated by Django 4.2.7 on 2025-09-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial_squashed_0013_remove_customer_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='waitlist_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vị trí trong danh sách chờ'),
        ),
    ]
