# Generated by Django 4.2.7 on 2025-09-19 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('financials', '0001_initial'), ('financials', '0002_initial'), ('financials', '0003_remove_payment_service_payment_services'), ('financials', '0004_auto_20250918_1109'), ('financials', '0005_auto_20250918_1112'), ('financials', '0006_auto_20250918_1113'), ('financials', '0007_remove_expense_created_by_remove_payment_appointment_and_more')]

    dependencies = [
        ('customers', '0002_initial'),
        ('appointments', '0002_initial'),
        ('customers', '0010_create_sample_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Số tiền')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('bank_transfer', 'Chuyển khoản'), ('insurance', 'Bảo hiểm'), ('other', 'Khác')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.branch', verbose_name='Chi nhánh')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Khách hàng')),
                ('services', models.ManyToManyField(blank=True, to='customers.service', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Số tiền')),
                ('category', models.CharField(choices=[('supplies', 'Vật tư'), ('equipment', 'Thiết bị'), ('rent', 'Thuê mặt bằng'), ('utilities', 'Tiện ích'), ('salary', 'Lương'), ('marketing', 'Marketing'), ('other', 'Khác')], max_length=20, verbose_name='Danh mục')),
                ('expense_date', models.DateField(verbose_name='Ngày chi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.branch', verbose_name='Chi nhánh')),
            ],
            options={
                'verbose_name': 'Chi phí',
                'verbose_name_plural': 'Chi phí',
                'ordering': ['-expense_date'],
            },
        ),
    ]
