# Generated by Django 4.2.7 on 2025-09-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Số tiền')),
                ('category', models.CharField(choices=[('supplies', 'Vật tư'), ('equipment', 'Thiết bị'), ('rent', 'Thuê mặt bằng'), ('utilities', 'Tiện ích'), ('salary', 'Lương'), ('marketing', 'Marketing'), ('other', 'Khác')], max_length=20, verbose_name='Danh mục')),
                ('expense_date', models.DateField(verbose_name='Ngày chi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chi phí',
                'verbose_name_plural': 'Chi phí',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Số tiền')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Số tiền đã trả')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('bank_transfer', 'Chuyển khoản'), ('insurance', 'Bảo hiểm'), ('other', 'Khác')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('partial', 'Thanh toán một phần'), ('refunded', 'Đã hoàn tiền'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Số tiền')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('bank_transfer', 'Chuyển khoản'), ('insurance', 'Bảo hiểm'), ('other', 'Khác')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lịch sử thanh toán',
                'verbose_name_plural': 'Lịch sử thanh toán',
                'ordering': ['-created_at'],
            },
        ),
    ]
