# Generated by Django 4.2.7 on 2025-09-10 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('customers', '0002_initial'),
        ('financials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tạo bởi'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='financials.payment', verbose_name='Thanh toán'),
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Lịch hẹn'),
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.branch', verbose_name='Chi nhánh'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Tạo bởi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.service', verbose_name='Dịch vụ'),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.branch', verbose_name='Chi nhánh'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Tạo bởi'),
        ),
    ]
