# Generated by Django 4.2.7 on 2025-09-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_create_sample_services'),
        ('financials', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='service',
        ),
        migrations.AddField(
            model_name='payment',
            name='services',
            field=models.ManyToManyField(blank=True, to='customers.service', verbose_name='Dịch vụ'),
        ),
    ]
