# Generated by Django 4.2.7 on 2025-09-10 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chi nhánh')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chi nhánh',
                'verbose_name_plural': 'Chi nhánh',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Thời gian (phút)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=100, verbose_name='Họ')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Tiền sử bệnh')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Dị ứng')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.branch', verbose_name='Chi nhánh')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
