# Generated by Django 4.2.7 on 2025-09-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='level',
            field=models.CharField(default='Standard', max_length=50, verbose_name='Cấp độ'),
        ),
    ]
