# Generated by Django 4.2.7 on 2025-09-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_service_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['parent__name', 'name', 'level_number'], 'verbose_name': 'Dịch vụ', 'verbose_name_plural': 'Dịch vụ'},
        ),
        migrations.AddField(
            model_name='service',
            name='level_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cấp độ số'),
        ),
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='customers.service', verbose_name='Danh mục cha'),
        ),
    ]
