# Generated by Django 4.2.7 on 2025-09-10 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_service_options_service_level_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.service', verbose_name='Dịch vụ ưu tiên'),
        ),
    ]
