# Generated by Django 4.2.7 on 2025-09-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_preferred_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name', 'level_number'], 'verbose_name': 'Dịch vụ', 'verbose_name_plural': 'Dịch vụ'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='parent',
        ),
    ]
