# Generated by Django 4.2.7 on 2025-09-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_service_options_remove_service_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='preferred_service',
        ),
        migrations.AddField(
            model_name='customer',
            name='services_used',
            field=models.ManyToManyField(blank=True, related_name='customers', to='customers.service', verbose_name='Dịch vụ sử dụng'),
        ),
    ]
