# Generated by Django 4.2.7 on 2025-09-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('customers', '0007_remove_customer_preferred_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='address_old',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ cũ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.province', verbose_name='Tỉnh/Thành phố'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Số nhà, tên đường'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.ward', verbose_name='Phường/Xã'),
        ),
    ]
