# Generated by Django 4.2.7 on 2025-09-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('customers', '0010_create_sample_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Đang CS'), ('inactive', 'Ngừng CS'), ('lead', 'Tiềm năng')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.province', verbose_name='Tỉnh/Thành'),
        ),
    ]
