# Generated by Django 4.2.7 on 2025-09-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customer_status_alter_customer_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Đang CS'), ('inactive', 'Ngừng CS'), ('lead', 'Tiềm năng'), ('success', 'Thành công')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
