# Generated by Django 4.2.7 on 2025-09-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Đang chăm sóc'), ('inactive', 'Ngưng chăm sóc'), ('success', 'Thành công')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
