# Generated by Django 4.2.7 on 2025-09-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial_squashed_0019_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Mã dịch vụ'),
            preserve_default=False,
        ),
    ]
