# Generated by Django 4.2.7 on 2025-09-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_service_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá'),
        ),
    ]
