# Generated by Django 4.2.7 on 2025-09-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('implant', 'Trồng răng implant'), ('crown', 'Bọc răng sứ'), ('orthodontic', 'Niềng răng'), ('other', 'Dịch vụ khác')], default='other', max_length=20, verbose_name='Danh mục'),
        ),
    ]
