# Generated by Django 4.2.7 on 2025-09-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_add_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
    ]
