# Generated by Django 4.2.7 on 2025-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID đơn vị hành chính')),
                ('full_name', models.CharField(max_length=200, verbose_name='Tên đầy đủ')),
                ('full_name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên đầy đủ tiếng Anh')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên viết tắt')),
                ('short_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên viết tắt tiếng Anh')),
                ('code_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã tên')),
                ('code_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã tên tiếng Anh')),
            ],
            options={
                'verbose_name': 'Đơn vị hành chính',
                'verbose_name_plural': 'Đơn vị hành chính',
                'db_table': 'administrative_units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdministrativeRegion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID vùng hành chính')),
                ('name', models.CharField(max_length=100, verbose_name='Tên vùng')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên vùng tiếng Anh')),
                ('code_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã tên')),
                ('code_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã tên tiếng Anh')),
            ],
            options={
                'verbose_name': 'Vùng hành chính',
                'verbose_name_plural': 'Vùng hành chính',
                'db_table': 'administrative_regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã tỉnh/thành phố')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tỉnh/thành phố')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên tiếng Anh')),
                ('full_name', models.CharField(max_length=200, verbose_name='Tên đầy đủ')),
                ('full_name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên đầy đủ tiếng Anh')),
                ('code_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã tên')),
                ('administrative_unit', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to='locations.administrativeunit', verbose_name='Đơn vị hành chính')),
            ],
            options={
                'verbose_name': 'Tỉnh/Thành phố',
                'verbose_name_plural': 'Tỉnh/Thành phố',
                'ordering': ['name'],
                'db_table': 'location_provinces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã phường/xã')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phường/xã')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên tiếng Anh')),
                ('full_name', models.CharField(max_length=200, verbose_name='Tên đầy đủ')),
                ('full_name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên đầy đủ tiếng Anh')),
                ('code_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã tên')),
                ('province', models.ForeignKey(db_column='province_code', default='01', on_delete=models.deletion.CASCADE, to='locations.province', verbose_name='Tỉnh/Thành phố')),
                ('administrative_unit', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to='locations.administrativeunit', verbose_name='Đơn vị hành chính')),
            ],
            options={
                'verbose_name': 'Phường/Xã',
                'verbose_name_plural': 'Phường/Xã',
                'ordering': ['name'],
                'db_table': 'location_wards',
                'managed': False,
            },
        ),
    ]
