# Generated by Django 4.2.7 on 2025-09-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_user_bio_user_date_of_birth_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Quản lý'), ('doctor', 'Bác sĩ'), ('receptionist', 'Nhân viên tư vấn & Lễ tân')], default='receptionist', max_length=20),
        ),
    ]
