# Generated by Django 4.2.7 on 2025-09-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250915_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Quản lý'), ('doctor', 'Bác sĩ'), ('creceptionist', 'Nhân viên tư vấn & Lễ tân')], default='receptionist', max_length=20),
        ),
    ]
