# Generated by Django 4.2.7 on 2025-09-15 03:07

from django.db import migrations
from django.contrib.auth import get_user_model

User = get_user_model()


def update_receptionist_role(apps, schema_editor):
    """Update receptionist role to creceptionist"""
    User.objects.filter(role='receptionist').update(role='creceptionist')


def reverse_update_receptionist_role(apps, schema_editor):
    """Reverse the role update"""
    User.objects.filter(role='creceptionist').update(role='receptionist')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(update_receptionist_role, reverse_update_receptionist_role),
    ]
